# Starship prompt theme
add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
style = "blue"
read_only = " "

[git_branch]
symbol = "🌱 "
style = "purple"

[git_status]
style = "yellow"

[package]
disabled = true

[username]
style_user = "bold cyan"
show_always = true
